import { createElement } from 'lwc';
import GetCaseRecordUsingUiRecordApi from 'c/getCaseRecordUsingUiRecordApi';

describe('c-get-case-record-using-ui-record-api', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-get-case-record-using-ui-record-api', {
            is: GetCaseRecordUsingUiRecordApi
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});